### ISSUE TITLE
Issue with variable product type

### ISSUE THREAD

**Issue by savemyname** [Vizir/blocks-for-products#1]
Hello, I've found and installed the Woocommerce product to use the Block editor. However, in case of variable product, if I change description with edit with Blocks and update, property and option are released. So I have to set properties and options again, and if I make any changes, they are released. 

The theme I'm using is the Block shop sold by Woocommerce and uses Wordpress 5.3.2. 
Please check.

**Comment by mariovalney** [comment]
Hi @savemyname . How are you?

I removed the text of your issue about demanding things, ok?

It's a free and open plugin so you can: 

- help translating
- help opening issues to make question or inform something
- help submitting code (PRs) do improve or fix something

So thank you to report.

**Comment by mariovalney** [comment]
Hi @savemyname . How are you?

Thank you for your report. :)

**Comment by mariovalney** [comment]
We are releasing the 1.1.0 version fixing that.

Thanks

**Comment by savemyname** [comment]
Thank you very much for your quick response. Now I can use it normally.
