### ISSUE TITLE
Embed Issue

### ISSUE THREAD

**Issue by savemyname** [Vizir/blocks-for-products#2]
Inserting youtube using the default block embed in the block editor results in wide spaces. Check and fix. 
<img width="1493" alt="스크린샷 2020-02-20 오후 2 14 50" src="https://user-images.githubusercontent.com/21188181/74903444-48622400-53ec-11ea-9793-ef5254a6a2a3.png">

**Comment by mariovalney** [comment]
Sounds like it's a editor or block issue.

Here is the editor repository: https://github.com/WordPress/gutenberg/issues
